name: Build and Test

on:
  push:
    paths: 
      - 'src/exercise.py'

jobs:
  
  get_test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with: 
        repository: ${{ secrets.TEN_THIRTY }}          
        token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
    - uses: actions/upload-artifact@v2
      with:                                                      
        path: lesson10/${{ secrets.T_E }}                                                                                    
     
  test:
    needs: get_test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - run: |
        python3 -m pip install --upgrade pip
        pip install pytest flake8
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - uses: actions/checkout@v2
    - uses: actions/download-artifact@v2  
    - run: python3 -m pytest    
      
  cleanup:
    needs: test
    if: always()
    runs-on: ubuntu-latest
    steps:
    - env:
        FOR_WEBHOOKS_SECRET: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
      run: |
        echo "::add-mask::$FOR_WEBHOOKS_SECRET"
        curl --s --S --L --request POST "https://api.github.com/repos/$GITHUB_REPOSITORY/dispatches" --header "Authorization: token $FOR_WEBHOOKS_SECRET" --header 'Content-Type: application/json' --header 'Accept: application/vnd.github.everest-preview+json' --data-raw "{ \"event_type\": \"cleanup\", \"client_payload\": {\"parent_runid\": \"$GITHUB_RUN_ID\", \"parent_repo\": \"$GITHUB_REPOSITORY\"} }"
    
