name: Build and Test

on:
  push:
    paths: 
      - 'src/exercise.py'

jobs:
  build:

    runs-on: ubuntu-latest

    steps: 

    - name: Checkout remote
      uses: actions/checkout@v2
      with: 
        repository: Professor-Ruiz/CS1030-Lesson-10
        token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
    - name: Upload Test
      uses: actions/upload-artifact@v2
      with: 
        name: test_exercise.py
        path: tests/test_exercise.py  
    - name: Checkout current
      uses: actions/checkout@v2
    - name: Remove current
      run: rm tests/test_exercise.py
    - name: Upload remote
      uses: actions/download-artifact@v2
      with: 
        name: test_exercise.py
        path: tests
    - name: Set up Python 3.x
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest flake8
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Test with pytest
      run: |
        python3 -m pytest
